In [1]:
#import modin.pandas as pd
import pandas as pd
import string as s
from os import listdir
from os.path import isfile, join
from tqdm import tqdm
import csv

In [2]:
#Takes a Series, groups by selected column and returns new List with most common values along with counts
#data: original dataset
#col: column to groupby
#threshold: minimum limit for value - count pair to be not a part of "others"
def group_others(data, col, threshold = 10):
    data = data.groupby([col]).size()
    others = 0
    data_w_others = []
    for key, val in data.iteritems():
        if (val < threshold):
            others += val
        else:
            data_w_others.append([key, val])
    if (threshold != 0):
        data_w_others.append(["Others", others])
    return data_w_others

In [14]:
#Dados para a categorização
#file = "Ano_Livro_Tipo_principais.csv"
file = "Ano_Livro_Tipo.csv"

key_file = pd.read_csv(file, header=None, encoding="ansi", sep=";")
header = key_file.iloc[0] #grab the first row for the header
key_file = key_file[1:] #take the data less the header row
key_file.columns = header
key_file = group_others(key_file, "Source title", 0)
key_file = pd.DataFrame(key_file, columns = ["Source", "Count"])

C:\Users\RHINES~1\AppData\Local\Temp/ipykernel_10708/1112684586.py:9: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for key, val in data.iteritems():

In [4]:
#Fonte de dados - subject area
file = "fontes//Subject Areas.csv"
subjects = pd.read_csv(file, header=None, encoding="ansi", sep=";")
header = subjects.iloc[0]
subjects = subjects[1:] 
subjects.columns = header
subjects["Description"] = subjects["Description"].str.strip()

In [5]:
#Fonte de dados - supergroup of given subject area
file = "fontes//Supergroup Subject Areas.csv"
supergroup = pd.read_csv(file, header=None, encoding="ansi", sep=";")
header = supergroup.iloc[0]
supergroup = supergroup[1:] 
supergroup.columns = header
supergroup["Supergroup"] = supergroup["Supergroup"].str.strip()

In [6]:
#Fonte de dados - conferencias
file = "fontes//Conferencias.csv"
conf = pd.read_csv(file, header=None, encoding="ansi", sep=";")
header = conf.iloc[0]
conf = conf[1:] 
conf.columns = header

C:\Users\RHINES~1\AppData\Local\Temp/ipykernel_10708/2751462232.py:3: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  conf = pd.read_csv(file, header=None, encoding="ansi", sep=";")

In [7]:
#Fonte de dados - subject area
file = "fontes//Revistas e jornais completo com subject areas.csv"
journals = pd.read_csv(file, header=None, encoding="ansi", sep=";")
header = journals.iloc[0] #grab the first row for the header
journals = journals[1:] #take the data less the header row
journals.columns = header

C:\Users\RHINES~1\AppData\Local\Temp/ipykernel_10708/2695651056.py:3: DtypeWarning: Columns (0,8) have mixed types. Specify dtype option on import or set low_memory=False.
  journals = pd.read_csv(file, header=None, encoding="ansi", sep=";")

In [8]:
journals.iloc[:,-31:]

,Top level: Life Sciences,Top level: Social Sciences,Top level: Physical Sciences,Top level: Health Sciences,1000 General,1100 Agricultural and Biological Sciences,1200 Arts and Humanities,"1300 Biochemistry, Genetics and Molecular Biology","1400 Business, Management and Accounting",1500 Chemical Engineering,...,2700 Medicine,2800 Neuroscience,2900 Nursing,"3000 Pharmacology, Toxicology and Pharmaceutics",3100 Physics and Astronomy,3200 Psychology,3300 Social Sciences,3400 Veterinary,3500 Dentistry,3600 Health Professions
1,NaN,Social Sciences,NaN,NaN,NaN,NaN,Arts and Humanities,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Physical Sciences,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Physics and Astronomy,NaN,NaN,NaN,NaN,NaN
3,Life Sciences,NaN,Physical Sciences,NaN,NaN,Agricultural and Biological Sciences,NaN,"Biochemistry, Genetics and Molecular Biology",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Physical Sciences,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,Physical Sciences,Health Sciences,NaN,NaN,NaN,NaN,NaN,NaN,...,Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43009,NaN,NaN,NaN,Health Sciences,NaN,NaN,NaN,NaN,NaN,NaN,...,Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43010,NaN,Social Sciences,NaN,NaN,NaN,NaN,Arts and Humanities,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Social Sciences,NaN,NaN,NaN
43011,Life Sciences,NaN,NaN,NaN,NaN,NaN,NaN,"Biochemistry, Genetics and Molecular Biology",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43012,Life Sciences,NaN,NaN,Health Sciences,NaN,NaN,NaN,"Biochemistry, Genetics and Molecular Biology",NaN,NaN,...,Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43013,Life Sciences,NaN,Physical Sciences,NaN,NaN,Agricultural and Biological Sciences,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
domain_dict = {}
supergroup_dict = {}
for value in key_file.values:
    title = value[0]
    count = value[1]
    for row in journals.values:
        source = row[1]
        if (title == source):
            for matching in row[-31:]:
                for domains in subjects.values:
                    if (matching == domains[1]):
                        if domain_dict.get(domains[1], None) != None:
                            domain_dict[domains[1]] += 1 
                        else:
                            domain_dict[domains[1]] = 1
                
                #for domains in supergroup.values:
                #    if (matching == domains[0]):
                #        if supergroup_dict.get(domains[0], None) != None:
                #            supergroup_dict[domains[0]] += 1 
                #        else:
                #            supergroup_dict[domains[0]] = 1

    #CONFERENCIAS, VER SE UTILIZA-SE OU NAO        
    #for row in conf.values:
    #    source = row[2]
    #    if (title == source):
    #        for matching in row[-27:]:
    #            for domains in conf.values:
    #                if (matching == domains[2]):
    #                    if domain_dict.get(domains[2], None) != None:
    #                        
    #                        domain_dict[domains[2]] += 1 
    #                    else:
    #                        domain_dict[domains[2]] = 0
    #                
    #print(journals.where("Source Title" == title))
    #print(value["Source"], " - ", value["Count"])

In [16]:
domain_dict

{'Computer Science': 230,
 'Engineering': 122,
 'Medicine': 62,
 'Health Professions': 10,
 'Biochemistry, Genetics and Molecular Biology': 25,
 'Materials Science': 16,
 'Physics and Astronomy': 18,
 'Social Sciences': 156,
 'Arts and Humanities': 17,
 'Chemical Engineering': 11,
 'Mathematics': 56,
 'Chemistry': 13,
 'Environmental Science': 21,
 'Energy': 15,
 'Immunology and Microbiology': 3,
 'Psychology': 10,
 'Decision Sciences': 24,
 'Neuroscience': 11,
 'Business, Management and Accounting': 15,
 'Economics, Econometrics and Finance': 7,
 'Earth and Planetary Sciences': 15,
 'General': 8,
 'Agricultural and Biological Sciences': 10,
 'Dentistry': 1}

In [17]:
#Takes dict, name of file and column names as arguments. 
#Saves dict onto csv file
def save_dict(data, name, cols):
    
    domain = []
    for key, value in data.items():
        domain.append([key, value])

    domain = pd.DataFrame(domain, columns = cols)

    domain.to_csv(name, index=False, sep=";", encoding="ansi")

In [18]:
save_dict(domain_dict, "subject area principais.csv", ["Subject area", "Count"])
save_dict(supergroup_dict, "supergroup principais.csv", ["Supergroup", "Count"])

In [19]:
domain_dict

{'Computer Science': 230,
 'Engineering': 122,
 'Medicine': 62,
 'Health Professions': 10,
 'Biochemistry, Genetics and Molecular Biology': 25,
 'Materials Science': 16,
 'Physics and Astronomy': 18,
 'Social Sciences': 156,
 'Arts and Humanities': 17,
 'Chemical Engineering': 11,
 'Mathematics': 56,
 'Chemistry': 13,
 'Environmental Science': 21,
 'Energy': 15,
 'Immunology and Microbiology': 3,
 'Psychology': 10,
 'Decision Sciences': 24,
 'Neuroscience': 11,
 'Business, Management and Accounting': 15,
 'Economics, Econometrics and Finance': 7,
 'Earth and Planetary Sciences': 15,
 'General': 8,
 'Agricultural and Biological Sciences': 10,
 'Dentistry': 1}

In [20]:
src_title = group_others(key_file, "Source title")
src_title = pd.DataFrame(src_title, columns = ["Source", "Count"])

KeyError: 'Source title'

In [21]:
print(src_title.sort_values(by=["Count"], ascending=False))

NameError: name 'src_title' is not defined

In [22]:
#Guardar os vários documentos vistos até agora para posterior análise em Excel
save_file = "year.csv"
year.to_csv(save_file, index=False, sep=";", encoding="ansi")

save_file = "contagem de dominio.csv"
domain.to_csv(save_file, index=False, sep=";", encoding="ansi")

save_file = "doc.csv"
doc_type.to_csv(save_file, index=False, sep=";", encoding="ansi")

NameError: name 'year' is not defined

In [ ]:
pair = []
cols = ["Keyword", "Count"]
for key, value in keyword_count.items():
    key_count = [key, value]
    pair.append(key_count)

In [ ]:
pair_final = pd.DataFrame(pair, columns=cols)
save_file = "Keywords_final.csv"
pair_final.to_csv(save_file, index=False, sep=";", encoding="ansi")